# Generated by Django 5.2 on 2025-12-17 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(max_length=50, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de contacto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_apellido',
            field=models.CharField(max_length=120, verbose_name='Nombre y Apellido'),
        ),
    ]
