# Generated by Django 5.2 on 2025-12-18 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=120, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de contacto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha'],
            },
        ),
    ]
