# Generated by Django 6.0 on 2025-12-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_destino_evento_imagen_recomendacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categotia',
            new_name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ('-fecha',)},
        ),
    ]
