# Generated by Django 6.0 on 2025-12-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_crearpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crearpost',
            name='creado',
        ),
        migrations.AddField(
            model_name='crearpost',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crearpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='crearpost',
            name='publicado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='crearpost',
            name='subtitulo',
            field=models.CharField(max_length=250),
        ),
    ]
